"""
NGX Signal — PDF Intelligence Reports (Pro Plan)
Generates downloadable AI-powered market analysis PDFs.
Covers: weekly market brief, stock deep-dives, sector reports.
"""
import io
import os
import requests
import streamlit as st
from datetime import date, datetime
from app.utils.supabase_client import get_supabase

PAID_PLANS  = {"starter", "trader", "pro"}
PRO_ONLY    = {"pro"}
GROQ_KEY    = os.environ.get("GROQ_API_KEY", "")
GEMINI_KEY  = os.environ.get("GEMINI_API_KEY", "")


def call_ai(prompt: str, max_tokens: int = 1200) -> str:
    """Call Groq or Gemini for report generation."""
    if GROQ_KEY:
        try:
            r = requests.post(
                "https://api.groq.com/openai/v1/chat/completions",
                json={"model": "llama-3.1-8b-instant",
                      "messages": [{"role": "user", "content": prompt}],
                      "max_tokens": max_tokens, "temperature": 0.6},
                headers={"Authorization": f"Bearer {GROQ_KEY}", "Content-Type": "application/json"},
                timeout=30
            )
            if r.status_code == 200:
                return r.json()["choices"][0]["message"]["content"]
        except Exception:
            pass
    if GEMINI_KEY:
        try:
            r = requests.post(
                f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key={GEMINI_KEY}",
                json={"contents": [{"parts": [{"text": prompt}]}],
                      "generationConfig": {"maxOutputTokens": max_tokens}},
                timeout=30
            )
            if r.status_code == 200:
                return r.json()["candidates"][0]["content"]["parts"][0]["text"]
        except Exception:
            pass
    return "AI analysis temporarily unavailable. Please try again shortly."


def generate_pdf_bytes(title: str, content: str, report_type: str) -> bytes:
    """
    Generate a styled PDF using pure Python (no external PDF libs).
    Returns PDF bytes using reportlab if available, else HTML bytes.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
        from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY

        buf    = io.BytesIO()
        doc    = SimpleDocTemplate(buf, pagesize=A4,
                                   leftMargin=2.2*cm, rightMargin=2.2*cm,
                                   topMargin=2*cm, bottomMargin=2*cm)
        styles = getSampleStyleSheet()

        BLACK  = HexColor("#000000")
        WHITE  = HexColor("#FFFFFF")
        GOLD   = HexColor("#F0A500")
        GREY   = HexColor("#A0A0A0")
        LGREY  = HexColor("#1A1A1A")

        title_style = ParagraphStyle("NGXTitle", parent=styles["Heading1"],
            fontSize=24, textColor=GOLD, spaceAfter=6, spaceBefore=0,
            fontName="Helvetica-Bold")
        sub_style = ParagraphStyle("NGXSub", parent=styles["Normal"],
            fontSize=11, textColor=WHITE, spaceAfter=16)
        h2_style = ParagraphStyle("NGXH2", parent=styles["Heading2"],
            fontSize=14, textColor=WHITE, spaceAfter=6, spaceBefore=14,
            fontName="Helvetica-Bold")
        body_style = ParagraphStyle("NGXBody", parent=styles["Normal"],
            fontSize=10, textColor=WHITE, spaceAfter=8, leading=15,
            alignment=TA_JUSTIFY)
        disc_style = ParagraphStyle("NGXDisc", parent=styles["Normal"],
            fontSize=8, textColor=GREY, spaceAfter=4, leading=12)

        story = []

        # Header
        story.append(Paragraph("NGX <font color='#F0A500'>Signal</font>", title_style))
        story.append(Paragraph(
            f"{title}  ·  {date.today().strftime('%d %B %Y')}",
            sub_style
        ))
        story.append(HRFlowable(width="100%", thickness=1, color=GOLD, spaceAfter=16))

        # Content — split by newlines into paragraphs
        for block in content.strip().split("\n\n"):
            block = block.strip()
            if not block:
                continue
            if block.startswith("##"):
                story.append(Paragraph(block.replace("##","").strip(), h2_style))
            elif block.startswith("#"):
                story.append(Paragraph(block.replace("#","").strip(), h2_style))
            else:
                story.append(Paragraph(block.replace("\n","<br/>"), body_style))
            story.append(Spacer(1, 4))

        story.append(Spacer(1, 20))
        story.append(HRFlowable(width="100%", thickness=0.5, color=LGREY, spaceAfter=8))
        story.append(Paragraph(
            "⚠️ This report is generated by NGX Signal AI and is for educational "
            "and informational purposes only. It does not constitute financial advice. "
            "Past performance is not indicative of future results. Always consult a "
            "licensed stockbroker before making investment decisions.",
            disc_style
        ))
        story.append(Paragraph(
            f"© {date.today().year} NGX Signal · ngxsignal.streamlit.app · "
            f"Generated {datetime.now().strftime('%d %b %Y %H:%M')} WAT",
            disc_style
        ))

        doc.build(story)
        return buf.getvalue()

    except ImportError:
        # Fallback: return HTML as bytes (user can print to PDF from browser)
        html = f"""<!DOCTYPE html>
<html><head><meta charset='UTF-8'>
<style>
body{{margin:2cm;font-family:Arial,sans-serif;background:#fff;color:#111;}}
h1{{color:#F0A500;font-size:28px;margin-bottom:4px;}}
.sub{{color:#555;font-size:13px;margin-bottom:24px;border-bottom:2px solid #F0A500;padding-bottom:12px;}}
h2{{color:#111;font-size:16px;margin-top:24px;}}
p{{font-size:12px;line-height:1.7;text-align:justify;}}
.disc{{font-size:10px;color:#888;margin-top:40px;border-top:1px solid #ddd;padding-top:12px;}}
</style></head>
<body>
<h1>NGX Signal</h1>
<div class='sub'>{title} · {date.today().strftime('%d %B %Y')}</div>
{''.join(f"<p>{p.strip().replace(chr(10),'<br>')}</p>" for p in content.split(chr(10)+chr(10)) if p.strip())}
<div class='disc'>⚠️ Educational purposes only · Not financial advice ·
© {date.today().year} NGX Signal · ngxsignal.streamlit.app</div>
</body></html>"""
        return html.encode("utf-8")


def render():
    sb      = get_supabase()
    profile = st.session_state.get("profile", {})
    plan    = profile.get("plan", "free")
    name    = profile.get("full_name", "Investor").split()[0]

    st.markdown("""
    <div style='font-family:Space Grotesk,sans-serif;font-size:22px;font-weight:800;color:#FFFFFF;margin-bottom:4px;'>
        📄 Intelligence Reports
    </div>
    <div style='font-family:DM Mono,monospace;font-size:11px;color:#808080;
                text-transform:uppercase;letter-spacing:.1em;margin-bottom:20px;'>
        AI-generated market analysis · Downloadable PDF
    </div>
    """, unsafe_allow_html=True)

    # Plan gate
    if plan not in PAID_PLANS:
        st.markdown("""
        <div style='background:#0D0D0D;border:1px solid rgba(240,165,0,0.3);
                    border-radius:12px;padding:28px;text-align:center;
                    animation:ngx-glow-gold 4s ease-in-out infinite;'>
          <div style='font-size:40px;margin-bottom:12px;'>📄</div>
          <div style='font-family:Space Grotesk,sans-serif;font-size:20px;
                      font-weight:700;color:#FFFFFF;margin-bottom:8px;'>
            Intelligence Reports
          </div>
          <div style='font-family:DM Mono,monospace;font-size:13px;color:#E0E0E0;
                      line-height:1.7;margin-bottom:20px;max-width:480px;margin-left:auto;margin-right:auto;'>
            Get AI-generated PDF reports on the Nigerian market —
            weekly performance summaries, stock deep-dives, and sector analysis.
            Available on Starter plan and above.
          </div>
        </div>
        """, unsafe_allow_html=True)
        st.markdown("<div style='height:8px'></div>", unsafe_allow_html=True)
        if st.button("Upgrade to Access Reports — from ₦3,500/mo →",
                     key="rep_upgrade", type="primary", use_container_width=True):
            st.session_state.current_page = "settings"
            st.rerun()
        return

    # ── Report types ─────────────────────────────────
    st.markdown("""
    <div style='display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:24px;'>
    """, unsafe_allow_html=True)

    REPORTS = [
        {"key": "weekly",   "icon": "📊", "title": "Weekly Market Brief",
         "desc": "Full AI summary of the week's NGX performance — gainers, losers, ASI movement, sector rotation, and key themes.",
         "plan": "starter"},
        {"key": "deepdive", "icon": "🔍", "title": "Stock Deep-Dive",
         "desc": "Comprehensive single-stock analysis — technicals, fundamentals, signal history, peer comparison, and outlook.",
         "plan": "trader"},
        {"key": "sector",   "icon": "🏭", "title": "Sector Analysis",
         "desc": "Sector-by-sector performance breakdown — traffic light ratings, key stocks to watch, and macro context.",
         "plan": "starter"},
        {"key": "signals",  "icon": "⭐", "title": "Signal Summary Report",
         "desc": "All BUY/HOLD/AVOID signals from the past 7 days with reasoning, entry/target/stop-loss, and performance tracking.",
         "plan": "trader"},
        {"key": "morning",  "icon": "🌅", "title": "Morning Intelligence Pack",
         "desc": "Pre-market PDF delivered daily — overnight global cues, NGX watchlist stocks, and today's trade ideas.",
         "plan": "pro"},
        {"key": "evening",  "icon": "🌆", "title": "Evening Close Report",
         "desc": "Post-market PDF — full day recap, volume analysis, after-hours activity, and tomorrow's key levels.",
         "plan": "pro"},
    ]

    PLAN_RANK = {"free": 0, "starter": 1, "trader": 2, "pro": 3}
    user_rank = PLAN_RANK.get(plan, 0)

    for rep in REPORTS:
        req_rank  = PLAN_RANK.get(rep["plan"], 1)
        locked    = user_rank < req_rank
        border_c  = "rgba(240,165,0,0.25)" if not locked else "rgba(255,255,255,0.06)"
        lock_icon = "🔒 " if locked else ""
        plan_badge = f"<span style='background:rgba(240,165,0,.15);color:#F0A500;font-size:9px;font-weight:700;padding:2px 8px;border-radius:999px;text-transform:uppercase;margin-left:6px;'>{rep['plan'].upper()}</span>"

        st.markdown(f"""
        <div style='background:#0A0A0A;border:1px solid {border_c};border-radius:10px;
                    padding:16px;margin-bottom:8px;
                    {"opacity:0.55;" if locked else "animation:ngx-fade-in .4s ease both;"}'>
          <div style='font-size:22px;margin-bottom:6px;'>{rep['icon']}</div>
          <div style='font-family:Space Grotesk,sans-serif;font-size:15px;font-weight:700;
                      color:#FFFFFF;margin-bottom:4px;'>
            {lock_icon}{rep['title']}{plan_badge}
          </div>
          <div style='font-family:DM Mono,monospace;font-size:11px;color:#A0A0A0;line-height:1.6;'>
            {rep['desc']}
          </div>
        </div>
        """, unsafe_allow_html=True)

        if not locked:
            # Stock input for deep-dive
            symbol_input = ""
            if rep["key"] == "deepdive":
                symbol_input = st.text_input(
                    "Stock symbol", placeholder="e.g. GTCO",
                    key=f"sym_{rep['key']}"
                ).upper().strip()

            if st.button(f"Generate {rep['title']} →", key=f"gen_{rep['key']}", type="primary"):
                with st.spinner(f"Generating {rep['title']}... This takes 20–30 seconds"):
                    content = _generate_report_content(sb, rep["key"], symbol_input)
                    title   = rep["title"]
                    ext     = "pdf" if _has_reportlab() else "html"
                    fname   = f"NGX_Signal_{rep['key']}_{date.today().isoformat()}.{ext}"

                    pdf_bytes = generate_pdf_bytes(title, content, rep["key"])
                    mime = "application/pdf" if ext == "pdf" else "text/html"

                    st.download_button(
                        label=f"⬇️ Download {title}",
                        data=pdf_bytes,
                        file_name=fname,
                        mime=mime,
                        key=f"dl_{rep['key']}",
                    )
                    st.success(f"✅ {title} generated!")

                    # Show preview
                    with st.expander(f"Preview — {title}", expanded=True):
                        st.markdown(
                            f"<div style='font-family:DM Mono,monospace;font-size:12px;"
                            f"color:#E0E0E0;line-height:1.8;white-space:pre-wrap;"
                            f"background:#050505;border:1px solid #1F1F1F;"
                            f"border-radius:8px;padding:16px;max-height:400px;"
                            f"overflow-y:auto;'>{content[:2000]}{'...' if len(content)>2000 else ''}</div>",
                            unsafe_allow_html=True
                        )
        elif locked:
            st.caption(f"Requires {rep['plan'].capitalize()} plan or above")

        st.markdown("<div style='height:4px'></div>", unsafe_allow_html=True)


def _has_reportlab() -> bool:
    try:
        import reportlab
        return True
    except ImportError:
        return False


def _generate_report_content(sb, report_key: str, symbol: str = "") -> str:
    """Generate AI report content based on live Supabase data."""
    today = str(date.today())

    # Pull live data
    sm_res  = sb.table("market_summary").select("*").order("trading_date", desc=True).limit(1).execute()
    sm      = sm_res.data[0] if sm_res.data else {}
    asi     = float(sm.get("asi_index", 201156.86) or 201156.86)
    asi_chg = float(sm.get("asi_change_percent", 0) or 0)
    gainers = int(sm.get("gainers_count", 0) or 0)
    losers  = int(sm.get("losers_count", 0) or 0)

    lat_res  = sb.table("stock_prices").select("trading_date").order("trading_date", desc=True).limit(1).execute()
    lat_date = lat_res.data[0]["trading_date"] if lat_res.data else today
    pr_res   = sb.table("stock_prices").select("symbol,price,change_percent,volume").eq("trading_date", lat_date).limit(200).execute()
    prices   = pr_res.data or []

    seen = set(); uniq = []
    for p in prices:
        if p["symbol"] not in seen: seen.add(p["symbol"]); uniq.append(p)

    top_g = sorted([p for p in uniq if float(p.get("change_percent") or 0) > 0],
                   key=lambda x: float(x.get("change_percent", 0) or 0), reverse=True)[:5]
    top_l = sorted([p for p in uniq if float(p.get("change_percent") or 0) < 0],
                   key=lambda x: float(x.get("change_percent", 0) or 0))[:5]

    g_text = ", ".join(f"{p['symbol']} (+{float(p.get('change_percent',0)):.1f}%)" for p in top_g)
    l_text = ", ".join(f"{p['symbol']} ({float(p.get('change_percent',0)):.1f}%)" for p in top_l)

    # Get signal scores
    sig_res = sb.table("signal_scores").select("symbol,signal,stars,reasoning").order("score_date", desc=True).order("stars", desc=True).limit(10).execute()
    signals = sig_res.data or []
    sig_text = "\n".join(f"- {s['symbol']}: {s['signal']} ({s['stars']}★) — {(s.get('reasoning') or '')[:80]}" for s in signals[:6])

    # Symbol data for deep-dive
    sym_context = ""
    if symbol and report_key == "deepdive":
        sp_res = sb.table("stock_prices").select("price,change_percent,volume,trading_date").eq("symbol", symbol).order("trading_date", desc=True).limit(30).execute()
        sp     = sp_res.data or []
        if sp:
            prices_list = [float(p["price"]) for p in sp if p.get("price")]
            hi = max(prices_list) if prices_list else 0
            lo = min(prices_list) if prices_list else 0
            latest_price = float(sp[0].get("price", 0) or 0)
            sym_context = f"\nStock: {symbol} | Price: ₦{latest_price:,.2f} | 30d High: ₦{hi:,.2f} | 30d Low: ₦{lo:,.2f}\nData points: {len(sp)} sessions"

    # ── BUILD PROMPT ──────────────────────────────────
    base_context = f"""Nigerian Exchange (NGX) market data:
- NGX All-Share Index: {asi:,.2f} ({asi_chg:+.2f}%)
- Trading date: {lat_date}
- Gainers: {gainers} | Losers: {losers} | Total stocks: {len(uniq)}
- Top gainers: {g_text or 'N/A'}
- Top losers:  {l_text or 'N/A'}
- Signal scores (top):
{sig_text or 'No signals available'}
{sym_context}"""

    prompts = {
        "weekly": f"""You are a senior Nigerian capital markets analyst. Write a professional weekly market intelligence report for NGX Signal subscribers.

{base_context}

Write the report in this exact structure:
## Executive Summary
(2-3 sentences on the week's key theme)

## Market Performance
(ASI movement, breadth, volume analysis)

## Top Performers This Week
(Analysis of top gainers with context — why they moved)

## Key Laggards
(Analysis of losers — is it sector-wide or stock-specific?)

## Signal Intelligence
(Which signals generated the best opportunities this week)

## Sector Rotation
(Which sectors are gaining/losing institutional interest)

## Week Ahead — Key Themes
(3-4 things to watch next week on the NGX)

## Trading Opportunities
(2-3 specific stock ideas with rationale — not financial advice)

Write in professional but accessible English. Be specific to Nigerian market context. Total length: 600-800 words.""",

        "deepdive": f"""You are a senior equity analyst specialising in Nigerian stocks. Write a comprehensive deep-dive report on {symbol or 'GTCO'}.

{base_context}

Structure:
## Company Overview
(Business model, sector, listing history — Nigeria-specific context)

## Technical Analysis
(Price action, trend, key levels, volume patterns)

## Fundamental Snapshot
(What we can infer about valuation in the Nigerian context)

## Signal Analysis
(Current NGX Signal rating, reasoning, key drivers)

## Entry, Target & Risk
(Specific entry zone, price target, stop-loss, risk/reward — clearly labelled as educational)

## Risks to Watch
(Company-specific and macro risks relevant to Nigerian investors)

## Verdict
(Clear conclusion — educational only)

Length: 500-700 words. Nigeria-market focused.""",

        "sector": f"""You are a Nigerian capital markets strategist. Write a sector analysis report for NGX Signal.

{base_context}

Cover these NGX sectors with a traffic light rating (🟢 Bullish / 🟡 Mixed / 🔴 Bearish):

## Banking Sector
## Consumer Goods Sector
## Oil & Gas Sector
## Telecoms Sector
## Industrial / Cement Sector
## Insurance Sector

For each sector provide:
- Traffic light rating
- 1-2 key stocks to watch
- Key driver of current performance
- Outlook for next 30 days

End with:
## Overall Market Theme
(2-3 sentences on the dominant macro theme driving NGX right now)

Length: 500-600 words.""",

        "signals": f"""You are the head of research at NGX Signal. Write a signal performance summary report.

{base_context}

Structure:
## Signal Dashboard — {lat_date}
(Summary table of current signals by conviction level)

## Strong Buy Candidates
(Detailed breakdown of highest-conviction BUY signals with entry/target/stop)

## Hold Positions
(Stocks currently in HOLD — what to watch for a direction change)

## Caution & Avoid
(Stocks to avoid — with clear reasoning)

## Signal Accuracy Review
(How have recent BUY signals performed? Educational context)

## This Week's Best Setup
(The single highest-conviction trade setup on the NGX right now)

Length: 500-700 words. Always include: "Signals are educational only and not financial advice."
""",
        "morning": f"""You are an NGX Signal pre-market analyst. Write a morning intelligence pack for {date.today().strftime('%A, %d %B %Y')}.

{base_context}

Structure:
## 🌅 Good Morning — Pre-Market Brief
(Opening sentiment — bullish/bearish/mixed)

## Overnight Global Cues
(US markets, crude oil, emerging markets — and how they affect NGX today)

## NGX Watchlist — Today's Key Stocks
(5 stocks to monitor today with specific price levels to watch)

## Today's Trade Ideas
(2-3 setups with entry, target, stop — clearly educational)

## Key Risk to Watch Today
(One macro or company-specific risk that could disrupt today's session)

## Morning Verdict
(One sentence: What kind of trading day should we expect?)

Length: 400-500 words. Professional, concise, actionable.""",

        "evening": f"""You are an NGX Signal post-market analyst. Write an evening close intelligence report for {date.today().strftime('%A, %d %B %Y')}.

{base_context}

Structure:
## 🌆 Market Close Summary
(How did the day end — ASI, breadth, mood)

## Today's Standout Movers
(Deep-dive into the top 3 gainers and losers — why they moved)

## Volume Analysis
(Were today's moves backed by volume conviction?)

## Signals That Triggered Today
(Which NGX Signal alerts fired today — performance review)

## Tomorrow's Setup
(What to expect tomorrow — key stocks, levels, catalysts)

## End-of-Day Intelligence
(One key insight that smart money is probably thinking about tonight)

Length: 400-500 words. Thoughtful and analytical.""",
    }

    prompt = prompts.get(report_key, prompts["weekly"])
    return call_ai(prompt, max_tokens=1400)
